README.md, lib/rules/no-unsafe-innerhtml.js, tests/rules/no-unsafe-innerhtml.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1172446
=> Rename Tagged library to Sanitizer

lib/rules/no-unsafe-innerhtml.js, package.json, tests/rules/no-unsafe-innerhtml.js
doing this in a PR to prevent public breakage
=> try allowing binary expressions (being careful about recent changes to upstream eslint)

lib/rules/no-unsafe-innerhtml.js, tests/rules/no-unsafe-innerhtml.js
=> Bug 1198200: eslint gives up on some simple innerHTML assignments

.travis.yml, lib/rules/no-unsafe-innerhtml.js, package.json, tests/rules/no-unsafe-innerhtml.js
=> Prepare 1.0.15

lib/rules/no-unsafe-innerhtml.js
=> Fix 34  rm parent node allow expression

.gitignore, README.md, SCHEMA.md, lib/ruleHelper.js, lib/rules/method.js, lib/rules/property.js, package.json, tests/rules/method.js, tests/rules/property.js
As mentioned in #45 this is the customisation step
=> Custom rules setup

lib/rules/method.js, tests/rules/method.js, tests/rules/property.js
Hey @jonathanKingston can you take a look?
I think ThisExpressions pose no risk, but I'd like a second pair of eyes on this.
=> Allow ThisExpressions as allowed callables (fixes #71)

lib/rules/method.js, tests/rules/method.js
@jonathanKingston Can you review?
CCing @gijsk
=> Fix #79: disallow use of createContextualFragment (unless sanitized)

lib/ruleHelper.js, tests/rules/method.js
(Depends on #108)
This will need rebasing as it expects #108 (otherwise I wouldnt have tests to base this on)
=> Move default sanitizer to config - fixes #107

index.js, lib/ruleHelper.js, lib/rules/method.js, lib/rules/property.js, package-lock.json, package.json, tests/rules/method.js, tests/rules/property.js
(to be rebased after #118)
the internal api change wasnt too bad actually
=> Eslint 6 new parser-test api compat

package.json
I'm assuming you need a new release for the addons-linter, @rpl?
=> Releasing version 3.1.2

tests/rules/method.js
tiny review. hope this doesn't become too tedious, @rpl :-)
=> add test for unexpected caller

package-lock.json, package.json
This solely bumps the version number. It's about time, we cut a release, the last one was in October :)
Please take a look when you find the time, @rpl.
=> Bump to v3.1.5

lib/ruleHelper.js
This should be very typical refactor.
=> Refactor long if/else in isAllowedExpression into case/switch

package.json
this release for folks who are hampered by #188 (i.e., includes #189)
=> Release v.4.0.1 (minor bugfix release)

package-lock.json, package.json, yarn.lock
This clears out a security issue with a transitive dependency. The issue is low-severity and linter-developers only, which makes it OK to talk about in public :)
=> Update mocha (devDependency)

README.md
@mangs noted in #203 that the README could need an update, now that we 
have tests and promise to support setHTML.
=> Adjust README to talk about the Sanitizer API

lib/ruleHelper.js, tests/rules/method.js
=> Fix #207: Chase right-hand side of AssignmentExpression in normalizeMethodcall

package.json
Cutting a release. It's been a while since 4.0.1 and the AMO folks would like to make use of the fixes in e.g., #213
=> Releasing version 4.0.2

README.md
Update code fence language in readme to allow syntax colouring
=> Update Code fence language
