mozilla/eslint-plugin-no-unsanitized

lib/rules/no-unsafe-innerhtml.js
Opened up funcName to accept either values instead of just the property.name parameter by adding an OR condition
old method:
funcName can be callee.name or property.name. this caused a failure if 'property' didn't exist so property.name couldn't be accessed
new method:
if either callee.name or property.name exist, then proceed with normal logic to assign one of these to funcName
=> Bug expression.callee

lib/rules/no-unsafe-innerhtml.js, tests/rules/no-unsafe-innerhtml.js
I discovered this while working on mozilla/addons-linter. I know that `document.write()` without an argument is theoretically wrong code but eslint doesn't validate this so we have to take care of that ourselves.
Let me know if I should fix this differently somehow or if you need more information about this.
=> Allow linting of function invalid / unexpected arguments.

lib/rules/method.js, tests/rules/method.js
>            code: "  _tests.shift()();", 
makes the rule throw an exception.
This pull request fixes it and adds a test.
Also, error reporting was broken for those cases, so I fixed that while I was at it
=> rule should not barf on a CallExpression result being called again

lib/rules/method.js, lib/rules/property.js
ESLint v4.15.0 added an official location for rules to store a URL to their documentation in the rule metadata in eslint/eslint#9788. This adds the URL to all the existing rules so anything consuming them can
know where their documentation is without having to resort to external packages to guess.
=> Add URL to rule documentation to the metadata

lib/rules/method.js, tests/rules/method.js
The return value of a NewExpression can't be scanned so easily with a linter, so I'm allowing all NewExpressions.
Can you take a brief look @jonathanKingston?
=> Fix unexpected callee newexpression (fix #73)

lib/ruleHelper.js, package.json
I'm not sure what requirements this project has for bumping eslint, but we noticed that the eslint dependency was lagging behind the eslint project itself when we were introducing [no-unsanitized in kibana](https://github.com/elastic/kibana/pull/16477), so I figured I'd open a PR to get the process started.
Note, bumping eslint required a change to `runHelper` to make sure it could pass what I assume are new default linting behaviors in eslint 4.  Let me know if you'd prefer a different solution than relying on the defaults.
=> Update eslint to version 4.16.0 

package.json
As recommended by the [eslint documentation](https://eslint.org/docs/developer-guide/shareable-configs#publishing-a-shareable-config), moves eslint to peerDependencies and uses >= 3 version specifier to allow users flexibility. Also adds eslint to dev dependencies as it is used by this project.
=> move eslint to peer dependencies, loosen version requirements

lib/rules/method.js, package.json, tests/rules/method.js
Fixes #83
As @mozfreddyb pointed out, the spec seems to describe a node type of `ImportCall`, but all of the parsers available at http://astexplorer.net/ parse `import()` as a `CallExpression` with a callee of type `Import`, so I've used that type for the methods whitelist.
Hope that's alright, it works great.
=> allow `import()` calls

lib/ruleHelper.js, lib/rules/method.js, lib/rules/property.js
Currently no-unsanitized/method is creating a new RuleContext, and combining an array of rules for pretty much each CallExpression.
I think this can be avoided to help performance.
Using's ESLint TIMING=1 environment variable and running against mozilla-central, I saw no-unsanitized/method go from being in the top-ten rules at about 2.6 seconds to dropping completely out of the list to less than 1.5 seconds (unfortunately they don't report more than the top-ten).
=> Improve performance of no-unsanitized/method

README.md, index.js
You can see at https://eslint.org/docs/6.0.0/developer-guide/working-with-plugins#configs-in-plugins that `plugins` can be included within `configs` (we do so in various linting projects, e.g., `eslint-plugin-jsdoc`).
I also fixed mention of the config file which was misspelled (see https://eslint.org/docs/user-guide/configuring#configuration-file-formats ).
=> - Enhancement: Avoid need for `plugins` when using `extends`

lib/rules/method.js, tests/rules/method.js
=> add support for SequenceExpression, when calling. fixes #113

.travis.yml, package-lock.json, package.json
The change to eslint 6.x is an internal API change, so that will have to happen in a follow-up (leaving #116 open)
=> update to eslint 5.x, bump rule minor version

lib/rules/method.js, lib/rules/property.js
- Add `meta: {type: "problem"}` to `method` and `property` rules
For fixable rules, this would mean it would be usable with `--fix-type`: https://eslint.org/docs/user-guide/command-line-interface#fix-type . But I'm personally planning to take advantage of `meta.type` with my badge-making project https://github.com/brettz9/eslint-formatter-badger when ready, so that linting counts can be grouped by type. Anyways, it shouldn't hurt to specify the nature of the rule.
While there is inevitably some ambiguity (e.g., is the use of the rule *always* a problem?), this ambiguity is I think present with pretty much any linting rule, so I think the basic idea is that this can be more serious than a "suggestion" and is not of course just "layout", the other possibility.
=> Add meta.type "problem"

package-lock.json, package.json
ESLint 7 is out now, and updating is nice and simple. Also update the version of Mocha.
I did try updating babel-eslint to version 9 and 10, but they both cause the tests to fail, so I'll leave that for someone else to look into.
=> Update ESLint to v7 and Mocha to v7 as well. Allow peer dependencies to ESLint v7.

.eslintrc.json, package-lock.json, package.json
- Testing: Add nyc for checking coverage
- Linting: Lint all by default (can add an ignore file later to
save IDEs from auto-linting certain files); use a
recommended file extension (json)
- npm: Remove unneeded `./node_modules/.bin` (available to
local npm scripts automatically)
Btw, one general thing I didn't do that would be nice is having `engines` set.
=> - Testing: Add nyc for checking coverage

lib/rules/method.js, tests/rules/method.js
In this pull requests there are:
- a couple of additional test cases to explicitly cover the issue describe in #124 
- a draft for a proposed approach to deal with this scenario (to be evaluated and discussed as part of this pull request):
- while validating a CallExpression, if we do have an AssignmentExpression as the callee node 
- check if the AssignmentExpression has a MemberExpression on the right and, if it does, validate a fake call expression that does have the memberExpression as the callee node.
=> Special handling AssignmentExpression with a MemberExpression on the right node (fixes #124)

lib/ruleHelper.js, lib/rules/method.js, package-lock.json, package.json, tests/rules/method.js, tests/rules/property.js
This is one of the two operators required for adding typescript
support to eslint-plugin-no-unsanitized
Adds support for TSAsExpression and TSTypeAssertion nodes.  These are
noops.
Adds test cases to method.js to ensure the new behavior is not broken.
=> Adds Typescript support to eslint-plugin-no-unsanitized

lib/ruleHelper.js, lib/rules/method.js, package-lock.json, package.json, tests/rules/method.js
I need this for the patch for #147 , as it needs a more modern babel. Other parsers (e.g. acorn as used on https://astexplorer.net/ ) also use the `ImportExpression` node type.
=> Update babel requirements and deal with newer 'import' parsing

lib/rules/property.js, package-lock.json, package.json, tests/rules/property.js
Although in theory, assignment to `.innerHTML` where relevant should never have `.innerHTML` as `undefined` or `null`, we should probably err on the side of caution.
=> Check logical assignment operators (fixes #147)

lib/ruleHelper.js, tests/rules/method.js
As noted in https://github.com/mozilla/eslint-plugin-no-unsanitized/issues/135#issuecomment-701463062 , in modern parsers this should be OK as the "real" dynamic import cannot be renamed or called as a method.
=> Allow method calls of import (fixes #135)

tests/parsers/fantasy-callee.js, tests/parsers/fantasy-operator.js, tests/rules/method.js, tests/rules/property.js
Context and how eslint suggests we solve this is in https://github.com/eslint/eslint/issues/14776, but let me re-iterate for posterity:
We try be exhaustive in terms of Expressions we can analyze. In particular, we want to complain for expressions that are not within a list of allowed expressions. This helps maintain the security guarantees we provide in our plugin and acts as a forcing function to adopt new JavaScript Syntax in lock-step with the tooling that is used to check it.
So far, we haven't been able to test for this scenario because it's hard to come up with the unknowns about non-existing JavaScript source.
However, as per the eslint issue above we can just make stuff up and define a parser that returns an AST with completely hypothetical syntax. Writing your own parser was …
=> Add test for unexpected expressions

lib/ruleHelper.js, tests/rules/property.js
We do already expect "ArrowFunctionExpression" in normalizeMethodCall, and so it seems reasonable to also expect "CallExpression" (and return an empty method name as we are doing for the "ArrowFunctionExpression").
At the moment code like the one in the test case is triggering the additonal linting issue that we log for unexpected cases we would like to be reported as new issue in this repo.
=> fix: normalizeMethodCall should expect a CallExpression node

lib/ruleHelper.js, tests/rules/method.js, tests/rules/property.js
I realize this is quite a change, but it seems relatively easy and very useful :)
Issue #167 has a bit of an explanation and the tests carry a lot of the wright, but I'm still a bit concerned that this might break stuff.
For testing, I'll explore running this on popular repos that are alraedy using this rule.
=> Trace variables back to find allow-able expression (fix #167)

lib/ruleHelper.js, tests/rules/method.js, tests/rules/property.js
Fixes #188
---
This PR fixes the issue reported in #188 by checking that `node.init` is
valid before using it. From there, I added two test cases and the code
basically told me where to put them (i.e. valid or invalid lists).
=> Fix error when `node.init` is `null`

.github/workflows/ci.yml
node v12 leaves long-term support end of this month.
=> Change default branch to main, remove nodejs v12 support

tests/rules/method.js
#197 requested support for the built-in Sanitizer API.
As one of the co-editors, I know that only `element.setHTML()` is stable enough for support.
`sanitizeFor()` has been removed from Gecko and we still have not reached consensus on how to spec & ship `sanitize()`. So this commit doesn't completely fix #197 and will require future work if we end up shipping more than just setHTML.
=> Ensure Sanitizer API's setHTML() is allowed (see #197)

index.js
The usage example in README is incorrect. Could fix README, but this approach is easier to deal with (e.g., when you want to just add `files: [...]` to it). This is a breaking change, unfortunately.
=> Fix flat recommended

lib/ruleHelper.js, tests/rules/property.js
The `no-unsanitized/property` rule crashes with the following code:
```js
const scratchDiv = document.createElement("div");
function foo() {
let text = "";
// This next line causes "Maximum call stack size exceeded"
text = `${text}<p>`;
scratchDiv.innerHTML = text;
}
```
This PR fixes it by keeping track of expressions being checked and not revisiting them. 
<details><summary>Full error message (with user dir redacted):</summary>
<p>
Oops! Something went wrong! :(
ESLint: 9.17.0
RangeError: Maximum call stack size exceeded
Occurred while linting foo.js:6
Rule: "no-unsanitized/property"
at RuleHelper.isAllowedIdentifier (/Users/joebloggs/foo/node_modules/.pnpm/eslint-plugin-no-unsanitized@4.1.2_eslint@9.17.0_jiti@2.4.1_/node_modules/eslint-plugin-no-unsanitized/lib/ruleHelper.js:165:19)
at …
=> Fix: Enhance RuleHelper to prevent infinite recursion
